### ISSUE TITLE
Crash @ latest

### ISSUE THREAD

**Issue by JohnMcLear** [Pita/ueberDB#92]
```
[2016-06-15 13:49:34.766] [ERROR] console - TypeError: operation.callback is not a function
    at /home/jose/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:110:17
    at /home/jose/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:219:5
    at callbacks (/home/jose/etherpad-lite/src/node_modules/ueberdb2/node_modules/dirty/lib/dirty/dirty.js:238:18)
    at /home/jose/etherpad-lite/src/node_modules/ueberdb2/node_modules/dirty/lib/dirty/dirty.js:277:9
    at afterWrite (_stream_writable.js:346:3)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fs.js:1867:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:619:5)
```

**Comment by lpagliari** [comment]
I had the same issue today when trying to call `deletePad` API method from Etherpad. It looks like this is caused by the latest changes on [`CloneAndAtomicLayer.js`](https://github.com/Pita/ueberDB/commit/86ced9b3999ca6e46ec73bb93f6d9b1ec730d1b0#diff-9e3cb00339c294bfbee62dc2176d0b1aL164):  `deletePad` [does not provide a callback for `db.remove`](https://github.com/ether/etherpad-lite/blob/develop/src/node/db/Pad.js#L650-L651), but we're not expecting that. I'll work on a fix for it and submit a PR
